from typing import Literal


XhsCollectStatus = Literal[
    "SUCCESS",
    "PARTIAL_SUCCESS",
    "COLLECT_FAILED",
    "LOGIN_REQUIRED",
    "CAPTCHA_REQUIRED",
    "RATE_LIMITED",
    "UNSUPPORTED_URL",
    "PARSE_FAILED",
    "PROVIDER_NOT_CONFIGURED",
    "PROVIDER_TIMEOUT",
]

XhsSourceType = Literal["MEDIACRAWLER", "XHS_MCP", "BROWSER_EXTENSION", "MANUAL_RAW_LINK"]

SUCCESS_STATUSES = {"SUCCESS", "PARTIAL_SUCCESS"}
ALLOWED_SOURCE_TYPES = {"MEDIACRAWLER", "XHS_MCP", "BROWSER_EXTENSION", "MANUAL_RAW_LINK", "URL_COLLECT"}
