"""Agent 产品入口层结构化协议。"""

from app.agent.product_entry.prompts import (
    build_task_planner_system_prompt,
    build_task_planner_user_prompt,
    build_user_input_router_system_prompt,
    build_user_input_router_user_prompt,
)
from app.agent.product_entry.registry import ACTION_REGISTRY, INTENT_ACTION_MAPPING, UNSUPPORTED_ACTION_REGISTRY
from app.agent.product_entry.schemas import (
    Action,
    AgentChatRequest,
    AgentChatResponse,
    AgentInput,
    AgentPlanningResult,
    AgentResponseStatus,
    AllowedEffect,
    ConfirmationCard,
    ConfirmationRequirement,
    FeedbackAction,
    FeedbackPolarity,
    InputAttachment,
    InputType,
    Intent,
    ParamValidationResult,
    Plan,
    PlanStep,
    PlanValidationResult,
    RiskFlag,
    TargetType,
    TrustLevel,
    ValidationIssue,
    ValidationSeverity,
)
from app.agent.product_entry.validators import validate_plan_result, validate_router_result

__all__ = [
    "ACTION_REGISTRY",
    "INTENT_ACTION_MAPPING",
    "UNSUPPORTED_ACTION_REGISTRY",
    "Action",
    "AgentChatRequest",
    "AgentChatResponse",
    "AgentInput",
    "AgentPlanningResult",
    "AgentResponseStatus",
    "AllowedEffect",
    "ConfirmationCard",
    "ConfirmationRequirement",
    "FeedbackAction",
    "FeedbackPolarity",
    "InputAttachment",
    "InputType",
    "Intent",
    "ParamValidationResult",
    "Plan",
    "PlanStep",
    "PlanValidationResult",
    "RiskFlag",
    "TargetType",
    "TrustLevel",
    "ValidationIssue",
    "ValidationSeverity",
    "build_task_planner_system_prompt",
    "build_task_planner_user_prompt",
    "build_user_input_router_system_prompt",
    "build_user_input_router_user_prompt",
    "validate_plan_result",
    "validate_router_result",
]
