"""Agent 产品入口层结构化协议。"""

from app.agent.product_entry.confirmation import build_confirmation_card
from app.agent.product_entry.prompts import (
    build_task_planner_system_prompt,
    build_task_planner_user_prompt,
    build_user_input_router_system_prompt,
    build_user_input_router_user_prompt,
)
from app.agent.product_entry.llm_router import LLMUserInputRouter
from app.agent.product_entry.registry import ACTION_REGISTRY, INTENT_ACTION_MAPPING, UNSUPPORTED_ACTION_REGISTRY
from app.agent.product_entry.schemas import (
    Action,
    AgentChatRequest,
    AgentChatResponse,
    AgentInput,
    AgentPlanningResult,
    AgentResponseStatus,
    AllowedEffect,
    ConfirmationCard,
    ConfirmationRequirement,
    FeedbackAction,
    FeedbackPolarity,
    InputAttachment,
    InputType,
    Intent,
    ParamValidationResult,
    ParamSpec,
    ParamType,
    Plan,
    PlanStep,
    PlanValidationResult,
    RiskFlag,
    TargetType,
    TrustLevel,
    ValidationIssue,
    ValidationSeverity,
)
from app.agent.product_entry.task_planner import LLMTaskPlanner, apply_action_registry_constraints
from app.agent.product_entry.trace import (
    AgentEntryTrace,
    AgentEntryTraceEvent,
    AgentEntryTraceRecorder,
    AgentEntryTraceStage,
    mask_sensitive_text,
    summarize_payload,
    to_agent_trace_payload,
)
from app.agent.product_entry.validation_rules import ACTION_ALTERNATIVE_PARAM_GROUPS, ACTION_PARAM_SPECS
from app.agent.product_entry.validators import validate_action_params, validate_param_sources, validate_plan_params, validate_plan_result, validate_router_result

__all__ = [
    "ACTION_REGISTRY",
    "ACTION_ALTERNATIVE_PARAM_GROUPS",
    "ACTION_PARAM_SPECS",
    "INTENT_ACTION_MAPPING",
    "LLMUserInputRouter",
    "LLMTaskPlanner",
    "UNSUPPORTED_ACTION_REGISTRY",
    "Action",
    "AgentChatRequest",
    "AgentChatResponse",
    "AgentEntryTrace",
    "AgentEntryTraceEvent",
    "AgentEntryTraceRecorder",
    "AgentEntryTraceStage",
    "AgentInput",
    "AgentPlanningResult",
    "AgentResponseStatus",
    "AllowedEffect",
    "ConfirmationCard",
    "ConfirmationRequirement",
    "FeedbackAction",
    "FeedbackPolarity",
    "InputAttachment",
    "InputType",
    "Intent",
    "ParamValidationResult",
    "ParamSpec",
    "ParamType",
    "Plan",
    "PlanStep",
    "PlanValidationResult",
    "RiskFlag",
    "TargetType",
    "TrustLevel",
    "ValidationIssue",
    "ValidationSeverity",
    "build_task_planner_system_prompt",
    "build_task_planner_user_prompt",
    "build_confirmation_card",
    "build_user_input_router_system_prompt",
    "build_user_input_router_user_prompt",
    "apply_action_registry_constraints",
    "mask_sensitive_text",
    "summarize_payload",
    "to_agent_trace_payload",
    "validate_action_params",
    "validate_param_sources",
    "validate_plan_params",
    "validate_plan_result",
    "validate_router_result",
]
