export interface ResearchOpportunity { ref: number; title: string; angle: string; target_audience: string | null; evidence_summary: string; score: number; risk_level: string }
export interface ResearchDetail { ref: number; account_ref: number; name: string; topic: string | null; summary: string | null; status: string; findings: Record<string, unknown[]>; source_metadata: Record<string, unknown>; opportunities: ResearchOpportunity[]; warnings: string[]; limitations: string[]; created_at: string; updated_at: string }
export interface StrategyOpportunity { ref: number; source_opportunity_ref: number; topic: string; angle: string; target_audience: string | null; content_goal: string; why_now: string; suggested_hook: string; evidence_refs: Record<string, unknown>[]; constraints: string[] }
export interface StrategyDetail { ref: number; account_ref: number; research_ref: number; goal: string; audience: string; directions: Record<string, unknown>[]; rationale: string; evidence_refs: Record<string, unknown>[]; constraints: string[]; opportunities: StrategyOpportunity[]; created_at: string }
export interface DraftContentView { title: string; body: string; tags: string[]; cta: string | null }
export interface DraftVersionMetadata { ref: number; version: number; parent_version_ref: number | null; created_from: string | null; created_at: string; content: DraftContentView }
export interface DraftReviewSummary { ref: number; status: string; passed: boolean; score: number; risk_level: string; summary: string | null; created_at: string }
export interface DraftDetail { ref: number; account_ref: number; strategy_ref: number | null; opportunity_ref: number | null; content_goal: string | null; status: string; latest_version_ref: number | null; latest_version: number; current_content: DraftContentView; versions: DraftVersionMetadata[]; reviews: DraftReviewSummary[]; created_at: string; updated_at: string }
export interface PublishPackageResult { package_ref: number; draft_id: number; draft_version_id: number; version_number: number; title: string; body: string; suggested_tags: string[]; optional_publish_notes: string | null; generated_at: string | null }
export interface PublishedNoteResult { published_note_ref: number; draft_id: number; draft_version_id: number; version_number: number; publish_url: string; platform_note_id: string | null; published_at: string; bound_at: string | null; account_ref: number }
export interface PrivateMetricsWriteRequest { account_id: number; label: string; window_start: string; window_end: string; dm_count: number | null; wechat_add_count: number | null; consultation_count: number | null; deal_count: number | null; revenue: number | null }
export interface PrivateMetricSnapshotResult { snapshot_ref: number; published_note_ref: number; observed_at: string | null; window: { label: string; window_start: string; window_end: string }; metrics: Record<string, number | string | null>; provenance: 'USER_ATTRIBUTED' }
export interface MetricSnapshot { ref: number; window: string | null; values: Record<string, number | string | null>; source_type: string; collected_at: string }
export interface PublicationDetail { ref: number; account_ref: number; publish_url: string; platform: string; status: string; published_at: string | null; draft_ref: number; published_draft_version_ref: number | null; published_draft_version: number | null; published_content: DraftContentView | null; public_metrics: MetricSnapshot[]; private_metrics_status: 'AVAILABLE' | 'UNKNOWN'; private_metrics: MetricSnapshot[]; post_publish_review: null | { ref: number; status: string; result_status: string | null; summary: string | null; observed_facts: Record<string, unknown>[]; inferences: Record<string, unknown>[]; created_at: string }; strategy_candidates: Array<{ ref: number; statement: string; scope: string; status: string }>; created_at: string }

export interface PageMeta { page_no: number; page_size: number; total: number; pages: number }
export interface ListPage<T> extends PageMeta { items: T[] }
export interface ResearchSummary { ref: number; name: string; topic: string | null; status: string; created_at: string; updated_at: string }
export interface StrategySummary { ref: number; research_ref: number; goal: string; audience: string; created_at: string }
export interface DraftSummary { ref: number; title: string; version: number; status: string; updated_at: string }
export interface PublicationSummary { ref: number; draft_ref: number; draft_version_ref: number | null; version_number: number | null; title: string; status: string; published_at: string | null }
export interface ReviewSummary { ref: number; published_note_ref: number; status: string; result_status: string | null; created_at: string }
