"""create account profile table

Revision ID: 3b9677e3d978
Revises: 619673cfafd9
Create Date: 2026-09-06 19:27:59.551352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9677e3d978'
down_revision: Union[str, Sequence[str], None] = '619673cfafd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False, comment='账号名称'),
    sa.Column('platform', sa.String(length=32), nullable=False, comment='平台'),
    sa.Column('homepage_url', sa.String(length=512), nullable=True, comment='账号主页地址'),
    sa.Column('positioning', sa.Text(), nullable=False, comment='账号定位'),
    sa.Column('target_audience', sa.Text(), nullable=False, comment='目标用户'),
    sa.Column('business_model', sa.String(length=128), nullable=True, comment='商业模式'),
    sa.Column('main_product', sa.String(length=128), nullable=True, comment='核心产品'),
    sa.Column('lead_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='单个线索估值'),
    sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='平均客单价'),
    sa.Column('gross_profit', sa.Numeric(precision=10, scale=2), nullable=False, comment='单笔毛利'),
    sa.Column('primary_goal', sa.String(length=64), nullable=False, comment='主要目标'),
    sa.Column('tone_preference', sa.Text(), nullable=True, comment='内容风格偏好'),
    sa.Column('forbidden_topics', sa.Text(), nullable=True, comment='禁用内容方向'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_profile_id'), 'account_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_profile_id'), table_name='account_profile')
    op.drop_table('account_profile')
    # ### end Alembic commands ###
