"""create competitor analysis report table

Revision ID: 5858dc6da1be
Revises: f85b04c27621
Create Date: 2026-09-07 17:55:19.155221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5858dc6da1be'
down_revision: Union[str, Sequence[str], None] = 'f85b04c27621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_analysis_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='关联账号 ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='分析报告名称'),
    sa.Column('keyword', sa.String(length=128), nullable=True, comment='分析关键词'),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='分析数据来源'),
    sa.Column('target_metric', sa.String(length=32), nullable=False, comment='目标指标'),
    sa.Column('note_snapshot_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='参与分析的笔记快照 ID'),
    sa.Column('note_count', sa.Integer(), nullable=False, comment='参与分析的笔记数量'),
    sa.Column('top_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='高频标签'),
    sa.Column('title_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='标题模式'),
    sa.Column('high_performance_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='高表现笔记'),
    sa.Column('content_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='内容洞察'),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='创作建议'),
    sa.Column('summary', sa.Text(), nullable=True, comment='分析摘要'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='分析状态'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_analysis_report_id'), 'competitor_analysis_report', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_analysis_report_id'), table_name='competitor_analysis_report')
    op.drop_table('competitor_analysis_report')
    # ### end Alembic commands ###
