"""create xhs note snapshot table

Revision ID: f85b04c27621
Revises: 3b9677e3d978
Create Date: 2026-09-06 20:46:43.964990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f85b04c27621'
down_revision: Union[str, Sequence[str], None] = '3b9677e3d978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xhs_note_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='关联账号 ID，可为空'),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='数据来源类型'),
    sa.Column('keyword', sa.String(length=128), nullable=True, comment='采集关键词'),
    sa.Column('note_url', sa.String(length=1024), nullable=False, comment='笔记 URL'),
    sa.Column('note_id', sa.String(length=128), nullable=True, comment='笔记 ID'),
    sa.Column('author_name', sa.String(length=128), nullable=True, comment='作者名称'),
    sa.Column('author_homepage', sa.String(length=1024), nullable=True, comment='作者主页'),
    sa.Column('title', sa.String(length=512), nullable=True, comment='笔记标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='笔记正文'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='标签列表'),
    sa.Column('content_type', sa.String(length=32), nullable=False, comment='笔记内容类型'),
    sa.Column('cover_url', sa.String(length=1024), nullable=True, comment='封面图 URL'),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='图片 URL 列表'),
    sa.Column('image_count', sa.Integer(), nullable=False, comment='图片数量'),
    sa.Column('image_ocr_text', sa.Text(), nullable=True, comment='图片 OCR 合并文本'),
    sa.Column('image_ocr_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='逐图 OCR 结果'),
    sa.Column('merged_text', sa.Text(), nullable=True, comment='用于分析的合并文本'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='公开点赞数'),
    sa.Column('collect_count', sa.Integer(), nullable=True, comment='公开收藏数'),
    sa.Column('comment_count', sa.Integer(), nullable=True, comment='公开评论数'),
    sa.Column('publish_time', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('crawl_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='采集时间'),
    sa.Column('raw_hash', sa.String(length=64), nullable=True, comment='原始内容哈希'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='采集状态'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xhs_note_snapshot_id'), 'xhs_note_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_xhs_note_snapshot_note_id'), 'xhs_note_snapshot', ['note_id'], unique=False)
    op.create_index(op.f('ix_xhs_note_snapshot_note_url'), 'xhs_note_snapshot', ['note_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xhs_note_snapshot_note_url'), table_name='xhs_note_snapshot')
    op.drop_index(op.f('ix_xhs_note_snapshot_note_id'), table_name='xhs_note_snapshot')
    op.drop_index(op.f('ix_xhs_note_snapshot_id'), table_name='xhs_note_snapshot')
    op.drop_table('xhs_note_snapshot')
    # ### end Alembic commands ###
