from datetime import datetime
from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


RegenerateScope = Literal["title", "cover", "body", "image_script", "tags", "cta", "all"]


class DraftImageScriptItem(BaseModel):
    """Draft image script item."""

    index: int = Field(ge=1, description="Image index")
    title: str = Field(description="Image title")
    content: str = Field(description="Image content")
    visual_hint: str | None = Field(default=None, description="Visual hint")


class DraftGenerateV2Result(BaseModel):
    """Structured result generated by the draft LLM call."""

    title_candidates: list[str] = Field(min_length=3, description="Title candidates")
    recommended_title: str = Field(description="Recommended title")
    cover_text: str = Field(description="Cover main text")
    cover_subtitle: str | None = Field(default=None, description="Cover subtitle")
    body_text: str = Field(description="Body text")
    image_script: list[DraftImageScriptItem] = Field(min_length=4, description="Image script")
    tag_list: list[str] = Field(default_factory=list, description="Tags")
    keyword_list: list[str] = Field(default_factory=list, description="Keywords")
    cta_text: str | None = Field(default=None, description="CTA text")


class GenerateDraftV2Request(BaseModel):
    """Request for generating a draft from an approved experiment."""

    experiment_id: int
    user_requirement: str | None = None


class RegenerateDraftRequest(BaseModel):
    """Request for partial or full regeneration."""

    scope: RegenerateScope = "all"
    user_requirement: str | None = None


class CreateDraftVersionRequest(BaseModel):
    """Request for creating a manual draft version snapshot."""

    note: str | None = None


class ContentDraftV2Create(BaseModel):
    """Data required to create a V2 content draft."""

    experiment_id: int
    title: str
    body: str
    tags: list[str] = Field(default_factory=list)
    cover_text: str | None = None
    image_scripts: list[dict] = Field(default_factory=list)
    cta: str | None = None
    title_candidates: list[str] = Field(default_factory=list)
    recommended_title: str | None = None
    cover_subtitle: str | None = None
    body_text: str | None = None
    image_script: list[dict] = Field(default_factory=list)
    tag_list: list[str] = Field(default_factory=list)
    keyword_list: list[str] = Field(default_factory=list)
    cta_text: str | None = None
    version: int = 1
    status: str = "GENERATED"
    generation_context: dict = Field(default_factory=dict)
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    estimated_cost: Decimal = Decimal("0")
    raw_response_id: str | None = None


class DraftGenerationContextCreate(BaseModel):
    """Snapshot used to generate a draft."""

    draft_id: int | None = None
    account_id: int
    experiment_id: int
    content_opportunity_id: int | None = None
    account_snapshot: dict = Field(default_factory=dict)
    experiment_snapshot: dict = Field(default_factory=dict)
    opportunity_snapshot: dict = Field(default_factory=dict)
    strategy_memory_snapshot: dict = Field(default_factory=dict)
    risk_constraints: list[str] = Field(default_factory=list)
    user_requirement: str | None = None


class PromptRunLogCreate(BaseModel):
    """Data required to create a prompt run log."""

    prompt_template_id: int | None
    prompt_name: str
    prompt_version: str
    input_payload: dict = Field(default_factory=dict)
    input_summary: dict = Field(default_factory=dict)
    rendered_prompt: str
    output_text: str | None = None
    output_json: dict = Field(default_factory=dict)
    output_summary: dict = Field(default_factory=dict)
    model: str
    provider: str
    prompt_key: str | None = None
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    input_token_count: int = 0
    output_token_count: int = 0
    estimated_cost: Decimal = Decimal("0")
    latency_ms: int = 0
    is_mock: bool = False
    fallback_used: bool = False
    fallback_from: str | None = None
    raw_response_id: str | None = None
    status: str = "SUCCESS"
    error_message: str | None = None


class ContentDraftVersionCreate(BaseModel):
    """Data required to create a draft version snapshot."""

    draft_id: int
    version: int
    regenerate_scope: str = "all"
    draft_snapshot: dict = Field(default_factory=dict)
    prompt_run_log_id: int | None = None


class DraftGenerationContextResponse(BaseModel):
    """Response model for draft generation context."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    draft_id: int | None
    account_id: int
    experiment_id: int
    content_opportunity_id: int | None
    account_snapshot: dict
    experiment_snapshot: dict
    opportunity_snapshot: dict
    strategy_memory_snapshot: dict
    risk_constraints: list[str]
    user_requirement: str | None
    created_at: datetime


class ContentDraftVersionResponse(BaseModel):
    """Response model for draft version snapshot."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    draft_id: int
    version: int
    regenerate_scope: str
    draft_snapshot: dict
    prompt_run_log_id: int | None
    created_at: datetime


class PromptRunLogResponse(BaseModel):
    """Response model for prompt run log."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    prompt_template_id: int | None
    prompt_name: str
    prompt_version: str
    input_payload: dict
    input_summary: dict = Field(default_factory=dict)
    output_json: dict
    output_summary: dict = Field(default_factory=dict)
    model: str
    provider: str
    prompt_key: str | None = None
    total_tokens: int
    input_token_count: int = 0
    output_token_count: int = 0
    estimated_cost: Decimal
    latency_ms: int = 0
    is_mock: bool = False
    fallback_used: bool = False
    fallback_from: str | None = None
    raw_response_id: str | None
    status: str
    error_message: str | None
    created_at: datetime


class ContentDraftV2Response(BaseModel):
    """Response model for V2 content draft."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    experiment_id: int
    title_candidates: list[str]
    recommended_title: str | None
    cover_text: str | None
    cover_subtitle: str | None
    body_text: str | None
    image_script: list[dict]
    tag_list: list[str]
    keyword_list: list[str]
    cta_text: str | None
    version: int
    status: str
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    estimated_cost: Decimal
    raw_response_id: str | None
    created_at: datetime
    updated_at: datetime
    generation_context_record: DraftGenerationContextResponse | None = None
    versions: list[ContentDraftVersionResponse] = Field(default_factory=list)
