from enum import StrEnum


class DataStatus(StrEnum):
    """数据状态枚举，用于标记数据是否真实、缺失、部分可用或失败。"""

    REAL = "REAL"
    MANUAL = "MANUAL"
    MCP = "MCP"
    UNKNOWN = "UNKNOWN"
    NOT_PROVIDED = "NOT_PROVIDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED" 


class ProviderSourceType(StrEnum):
    """Provider 数据来源类型枚举，用于统一标记采集数据来源。"""

    XHS_PUBLIC_READONLY = "XHS_PUBLIC_READONLY"
    MCP_XHS = "MCP_XHS"
    MANUAL = "MANUAL"
    SEED_SAMPLE = "SEED_SAMPLE"
    UNKNOWN = "UNKNOWN"


class ProviderErrorCode(StrEnum):
    """Provider 错误码枚举，用于统一采集、MCP、LLM、人工录入和工作流失败原因。"""

    DATA_NOT_PROVIDED = "DATA_NOT_PROVIDED"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
    DATA_PARTIAL = "DATA_PARTIAL"
    DATA_FIELD_UNKNOWN = "DATA_FIELD_UNKNOWN"

    MCP_NOT_CONFIGURED = "MCP_NOT_CONFIGURED"
    MCP_PROVIDER_FAILED = "MCP_PROVIDER_FAILED"
    MCP_CALL_FAILED = "MCP_CALL_FAILED"
    MCP_TIMEOUT = "MCP_TIMEOUT"
    MCP_PARSE_FAILED = "MCP_PARSE_FAILED"
    MCP_TOOL_NOT_WHITELISTED = "MCP_TOOL_NOT_WHITELISTED"

    MANUAL_SNAPSHOT_REQUIRED = "MANUAL_SNAPSHOT_REQUIRED"
    PUBLIC_METRIC_MISSING = "PUBLIC_METRIC_MISSING"
    COMMENT_SAMPLE_MISSING = "COMMENT_SAMPLE_MISSING"
    COMMENT_SAMPLE_INSUFFICIENT = "COMMENT_SAMPLE_INSUFFICIENT"

    LLM_CONFIG_MISSING = "LLM_CONFIG_MISSING"
    LLM_PROVIDER_UNAVAILABLE = "LLM_PROVIDER_UNAVAILABLE"
    LLM_OUTPUT_PARSE_FAILED = "LLM_OUTPUT_PARSE_FAILED"
    LLM_SCHEMA_INVALID = "LLM_SCHEMA_INVALID"
    LLM_OUTPUT_FAILED = "LLM_OUTPUT_FAILED"

    WORKFLOW_BLOCKED = "WORKFLOW_BLOCKED"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    RISK_BLOCKED = "RISK_BLOCKED"
    COLLECTION_FAILED = "COLLECTION_FAILED"
