<template><AssetListShell title="Draft" description="查看草稿内容、版本状态，并继续编辑或发布" :account-ref="store.account_ref" :items="items" :loading="loading" :error="error" :page-no="pageNo" :page-size="pageSize" :total="total" @page-change="load"><template #default="{item}"><article class="draft-card"><div class="draft-main" @click="open(item.ref)"><div><strong>{{item.title}}</strong><small>草稿 {{item.ref}} · 更新于 {{formatTime(item.updated_at)}}</small></div><p>{{item.preview||'暂无正文预览'}}</p><div class="badges"><el-tag>最新 V{{item.version}}</el-tag><el-tag v-if="item.publishedVersion" type="success">已发布 V{{item.publishedVersion}}</el-tag><el-tag type="info">{{statusLabel(item.status)}}</el-tag></div></div><div class="draft-actions"><el-button @click="open(item.ref)">进入详情</el-button><el-button @click="select(item)">选择到对话</el-button><el-button v-if="canPublish(item.status)" type="primary" @click="open(item.ref)">前往发布</el-button></div></article></template></AssetListShell></template>
<script setup lang="ts">
import{onBeforeUnmount,onMounted,ref}from'vue';import{useRouter}from'vue-router';import AssetListShell from'@/components/AssetListShell.vue';import{getDraftDetail,getDraftList,getPublicationList}from'@/api/unifiedAgent';import{useAgentChatStore}from'@/stores/agentChat';import{formatTime,statusLabel}from'@/utils/presentation';import type{DraftSummary}from'@/types/productRead'
interface DraftCard extends DraftSummary{preview:string;publishedVersion:number|null}
const store=useAgentChatStore(),router=useRouter(),items=ref<DraftCard[]>([]),loading=ref(false),error=ref(''),pageNo=ref(1),pageSize=20,total=ref(0);let controller:AbortController|null=null
const open=(ref:number)=>router.push({ name: 'agentDraft', params: { draftRef:ref } });const canPublish=(status:string)=>!['PUBLISHED','FAILED'].includes(status)
const select=async(item:DraftCard)=>{store.setWorkspaceSelection({draft_ref:item.ref},{type:'草稿',title:item.title,version:`V${item.version}`,detail_route:`/agent/draft/${item.ref}`});await router.push(store.conversation_id?`/agent/chat/${store.conversation_id}`:'/agent/chat')}
async function load(page=1){if(!store.account_ref)return;controller?.abort();controller=new AbortController();loading.value=true;error.value='';try{const result=await getDraftList(store.account_ref,page,pageSize,controller.signal);const publications=await getPublicationList(store.account_ref,1,100,controller.signal);const published=new Map(publications.items.map(item=>[item.draft_ref,item.version_number]));items.value=await Promise.all(result.items.map(async item=>{const detail=await getDraftDetail(item.ref,store.account_ref!,controller!.signal);return{...item,version:detail.latest_version,preview:detail.current_content.body.slice(0,120),publishedVersion:published.get(item.ref)||null}}));total.value=result.total;pageNo.value=result.page_no}catch(reason){if((reason as Error).name!=='CanceledError')error.value='草稿列表加载失败，请稍后重试'}finally{loading.value=false}}
onMounted(()=>load());onBeforeUnmount(()=>controller?.abort())
</script>
<style scoped>.draft-card{display:grid;grid-template-columns:1fr auto;gap:18px;padding:16px;border:1px solid #e5e7eb;border-radius:10px}.draft-main{cursor:pointer}.draft-main strong,.draft-main small{display:block}.draft-main small,.draft-main p{color:#64748b}.draft-main p{margin:10px 0;line-height:1.6}.badges,.draft-actions{display:flex;align-items:center;gap:8px}.draft-actions{flex-direction:column;align-items:stretch;justify-content:center}</style>
