<template><ArtifactDetailShell kind="已发布内容" :title="data?.published_content?.title||'发布详情'" :artifact-ref="refId" :loading="loading" :error="error" :selection="{published_note_ref:refId}" selection-label="已发布内容" :selection-title="data?.published_content?.title" :selection-version="data?.published_draft_version?`实际发布 V${data.published_draft_version}`:undefined"><template v-if="data"><p class="intro">这是已经实际发布的内容。复盘始终使用下方“实际发布版本”，不会自动切换到草稿最新版本。</p><el-descriptions :column="2" border><el-descriptions-item label="发布链接"><a :href="data.publish_url" target="_blank" rel="noreferrer">打开小红书内容</a></el-descriptions-item><el-descriptions-item label="发布状态">{{statusLabel(data.status)}}</el-descriptions-item><el-descriptions-item label="实际发布版本">V{{data.published_draft_version??'未知'}}</el-descriptions-item><el-descriptions-item label="当前最新草稿版本">{{latestDraftVersion?`V${latestDraftVersion}`:'暂未读取'}}</el-descriptions-item></el-descriptions>
<h2>公开表现数据</h2><el-empty v-if="!data.public_metrics.length" description="暂无数据"/><el-card v-for="metric in data.public_metrics" :key="metric.ref" shadow="never"><strong>{{metric.window||'统计窗口'}}</strong><div class="metrics"><span v-for="(value,key) in metric.values" :key="key"><b>{{metricLabel(key)}}</b>{{displayMetric(value)}}</span></div><small>来源：{{sourceLabel(metric.source_type)}}</small></el-card>
<div class="section-title"><h2>用户填写的转化数据</h2><el-button type="primary" plain @click="metricsFormVisible=!metricsFormVisible">{{metricsFormVisible?'收起表单':'录入 / 更新数据'}}</el-button></div><el-alert v-if="data.private_metrics_status==='UNKNOWN'&&!data.private_metrics.length" title="暂无数据：用户尚未填写私信、加微、咨询、成交等转化结果" type="info" :closable="false"/><el-card v-for="metric in data.private_metrics" :key="metric.ref" shadow="never"><div class="metrics"><span v-for="(value,key) in metric.values" :key="key"><b>{{metricLabel(key)}}</b>{{displayMetric(value)}}</span></div><small>来源：{{sourceLabel(metric.source_type)}} · {{formatTime(metric.collected_at)}}</small></el-card>
<el-form v-if="metricsFormVisible" class="metrics-form" label-position="top"><div class="form-grid"><el-form-item label="统计窗口名称"><el-input v-model="form.label" placeholder="例如 D7"/></el-form-item><el-form-item label="统计时间范围"><el-date-picker v-model="form.window" type="datetimerange" value-format="YYYY-MM-DDTHH:mm:ss.SSSZ" start-placeholder="开始时间" end-placeholder="结束时间"/></el-form-item><el-form-item v-for="field in privateFields" :key="field.key" :label="field.label"><el-input-number v-model="form[field.key]" :min="0" controls-position="right"/></el-form-item></div><el-alert title="只填写你真实掌握的数据；未填写和 0 含义不同。" type="info" :closable="false"/><el-button type="primary" :loading="savingMetrics" :disabled="!canSaveMetrics" @click="saveMetrics">保存转化数据</el-button></el-form>
<div class="section-title"><h2>发布后复盘</h2><el-button type="primary" @click="startReview">开始复盘</el-button></div><el-empty v-if="!data.post_publish_review" description="尚未生成复盘；可选择当前已发布内容后回到 Agent 对话开始复盘"/><template v-else><el-descriptions :column="2" border><el-descriptions-item label="绑定的已发布内容">{{refId}}</el-descriptions-item><el-descriptions-item label="复盘状态">{{statusLabel(data.post_publish_review.result_status||data.post_publish_review.status)}}</el-descriptions-item></el-descriptions><h3>使用的数据来源</h3><p>公开表现数据 {{data.public_metrics.length}} 组；用户填写转化数据 {{data.private_metrics.length}} 组；绑定实际发布版本 V{{data.published_draft_version??'未知'}}。</p><h3>复盘结论</h3><p>{{data.post_publish_review.summary||'暂无结论摘要'}}</p><h3>事实与判断</h3><el-card shadow="never"><strong>已观察事实</strong><pre>{{pretty(data.post_publish_review.observed_facts)}}</pre><strong>分析判断</strong><pre>{{pretty(data.post_publish_review.inferences)}}</pre></el-card></template><h3>下一轮策略建议</h3><el-empty v-if="!data.strategy_candidates.length" description="暂无策略建议"/><el-card v-for="item in data.strategy_candidates" :key="item.ref" shadow="never"><strong>{{item.statement}}</strong><p>适用范围：{{item.scope}} · {{statusLabel(item.status)}}</p><small>建议引用：{{item.ref}}</small></el-card></template></ArtifactDetailShell></template>
<script setup lang="ts">
import{computed,onBeforeUnmount,onMounted,reactive,ref}from'vue';import{useRoute,useRouter}from'vue-router';import{getDraftDetail,getPublicationDetail,recordPrivateMetrics}from'@/api/unifiedAgent';import{useAgentChatStore}from'@/stores/agentChat';import{displayMetric,formatTime,metricLabel,sourceLabel,statusLabel}from'@/utils/presentation';import type{PublicationDetail}from'@/types/productRead';import ArtifactDetailShell from'@/components/ArtifactDetailShell.vue'
const route=useRoute(),router=useRouter(),store=useAgentChatStore(),refId=computed(()=>Number(route.params.publishedNoteRef)),loading=ref(true),error=ref(''),data=ref<PublicationDetail|null>(null),latestDraftVersion=ref<number|null>(null),controller=new AbortController(),metricsFormVisible=ref(false),savingMetrics=ref(false)
type MetricKey='dm_count'|'wechat_add_count'|'consultation_count'|'deal_count'|'revenue';const privateFields:{key:MetricKey;label:string}[]=[{key:'dm_count',label:'私信咨询数'},{key:'wechat_add_count',label:'微信新增数'},{key:'consultation_count',label:'有效咨询数'},{key:'deal_count',label:'成交数'},{key:'revenue',label:'成交金额'}];const form=reactive<{label:string;window:string[];dm_count:number|null;wechat_add_count:number|null;consultation_count:number|null;deal_count:number|null;revenue:number|null}>({label:'',window:[],dm_count:null,wechat_add_count:null,consultation_count:null,deal_count:null,revenue:null});const canSaveMetrics=computed(()=>Boolean(form.label&&form.window?.length===2&&privateFields.some(field=>form[field.key]!==null)))
const pretty=(value:unknown)=>Array.isArray(value)&&!value.length?'暂无':JSON.stringify(value,null,2)
async function load(){if(!store.account_ref){error.value='请先选择账号';loading.value=false;return}try{data.value=await getPublicationDetail(refId.value,store.account_ref,controller.signal);latestDraftVersion.value=(await getDraftDetail(data.value.draft_ref,store.account_ref,controller.signal)).latest_version}catch(e){if(!controller.signal.aborted)error.value=store.clearRejectedAccount(e)?'账号不可用，请重新选择账号':'发布详情加载失败'}finally{loading.value=false}}
async function saveMetrics(){if(!store.account_ref||!canSaveMetrics.value)return;savingMetrics.value=true;try{await recordPrivateMetrics(refId.value,{account_id:store.account_ref,label:form.label,window_start:form.window[0],window_end:form.window[1],dm_count:form.dm_count,wechat_add_count:form.wechat_add_count,consultation_count:form.consultation_count,deal_count:form.deal_count,revenue:form.revenue});metricsFormVisible.value=false;await load()}catch{error.value='转化数据保存失败，请检查时间范围和填写内容'}finally{savingMetrics.value=false}}
async function startReview(){store.setWorkspaceSelection({published_note_ref:refId.value},{type:'已发布内容',title:data.value?.published_content?.title||'已发布内容',version:data.value?.published_draft_version?`实际发布 V${data.value.published_draft_version}`:undefined,detail_route:route.fullPath});await router.push(store.conversation_id?`/agent/chat/${store.conversation_id}`:'/agent/chat')}
onMounted(load);onBeforeUnmount(()=>controller.abort())
</script>
<style scoped>.intro{color:#64748b;line-height:1.7}h2{margin-top:28px;font-size:18px}h3{margin-top:22px}.el-card{margin:8px 0}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:10px 0}.metrics span{display:grid;padding:10px;border-radius:8px;background:#f8fafc}.metrics b{color:#64748b;font-size:11px}.section-title{display:flex;align-items:center;justify-content:space-between;margin-top:20px}.section-title h2{margin:0}.metrics-form{display:grid;gap:12px;margin-top:12px;padding:16px;border:1px solid #dbeafe;border-radius:10px;background:#f8fbff}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}pre{white-space:pre-wrap;font-family:inherit;color:#475569}@media(max-width:700px){.metrics,.form-grid{grid-template-columns:1fr}}</style>
